# Generated by Django 4.0.5 on 2022-07-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_account_month_account_year_alter_account_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='month',
            field=models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='1', max_length=3),
        ),
        migrations.AlterField(
            model_name='account',
            name='year',
            field=models.TextField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024')], default='2022', max_length=5),
        ),
    ]
